# Generated by Django 3.0.3 on 2020-02-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websub', '0002_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
