# Generated by Django 2.2.6 on 2019-10-16 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='api.Guild')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('guild', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game_id', models.CharField(max_length=300, unique=True)),
                ('stream_url', models.URLField(blank=True, null=True)),
                ('guild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Guild')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='api.League')),
            ],
        ),
        migrations.CreateModel(
            name='SC2Profile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('profile_url', models.URLField()),
                ('avatar_url', models.CharField(max_length=300)),
                ('profile_id', models.CharField(max_length=100)),
                ('region_id', models.IntegerField()),
                ('realm_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.League')),
            ],
            options={
                'unique_together': {('league', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('sha256', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Match')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game_time', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value', models.IntegerField(default=0)),
                ('key', models.CharField(choices=[('player_leave', 'Player Leaving'), ('bunker_killed', 'Bunker Destroyed'), ('bunker started', 'Bunker Building'), ('match_end', 'Match Ending'), ('bunker_cancelled', 'Bunker Cancelled'), ('match_start', 'Match Starting'), ('WIN', 'Player Wins'), ('LOSS', 'Player Loses'), ('DRAW', 'Player Draws'), ('ADJ', 'Player Point Adjustment')], max_length=100)),
                ('raw', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='api.SC2Profile')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.Match')),
                ('opposing_handle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.SC2Profile')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='api.Season'),
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('team_number', models.IntegerField()),
                ('position_number', models.IntegerField()),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='api.Match')),
                ('sc2_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='api.SC2Profile')),
            ],
            options={
                'unique_together': {('match', 'sc2_profile', 'team_number', 'position_number')},
            },
        ),
    ]
