# Generated by Django 2.2.6 on 2019-10-18 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc2profile',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='sc2profile',
            name='realm_id',
        ),
        migrations.RemoveField(
            model_name='sc2profile',
            name='region_id',
        ),
        migrations.AddField(
            model_name='sc2profile',
            name='discord_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
