# Generated by Django 2.2.6 on 2019-10-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191018_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc2profile',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
