# Generated by Django 2.2.6 on 2019-10-18 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191018_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc2profile',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sc2profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
