# Generated by Django 2.2.6 on 2019-10-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191018_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('elo', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('toon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.SC2Profile')),
            ],
        ),
    ]
