# Generated by Django 2.2.6 on 2019-10-19 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
