# Generated by Django 2.2.6 on 2019-11-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191019_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
