# Generated by Django 2.2.6 on 2019-11-28 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191128_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='sc2_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.SC2Profile'),
        ),
    ]
