# Generated by Django 2.2.6 on 2019-12-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191128_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='replay',
            name='sha256',
        ),
        migrations.AlterField(
            model_name='roster',
            name='sc2_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='api.SC2Profile'),
        ),
        migrations.CreateModel(
            name='UnitStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('made', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('killed', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_stats', to='api.Match')),
                ('opposing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SC2Profile')),
                ('sc2_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_stats', to='api.SC2Profile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='arcade_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Game'),
        ),
    ]
