# Generated by Django 2.2.6 on 2019-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191219_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='map_name',
        ),
        migrations.AddField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='real_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
