# Generated by Django 3.0.1 on 2019-12-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191219_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='file',
            field=models.FileField(upload_to='replays'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay', to='api.Match'),
        ),
    ]
