# Generated by Django 3.0.1 on 2019-12-22 23:28

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191221_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replay',
            name='file',
            field=models.FileField(upload_to=api.models.upload_replay_to),
        ),
    ]
