# Generated by Django 3.0.1 on 2019-12-22 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191222_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replay',
            name='user',
        ),
        migrations.AddField(
            model_name='replay',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SC2Profile'),
        ),
    ]
