# Generated by Django 3.0.1 on 2020-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191223_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
