# Generated by Django 3.0.1 on 2020-01-10 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200110_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 2, 59, 20, 912997)),
        ),
    ]
