# Generated by Django 3.0.1 on 2020-01-10 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200110_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
