# Generated by Django 3.0.1 on 2020-01-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200110_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('connected', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.Match')),
                ('sc2_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SC2Profile')),
            ],
        ),
    ]
