# Generated by Django 3.0.2 on 2020-01-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_matchclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('abandoned', 'Abandoned'), ('final', 'Final')], default='initial', max_length=50),
        ),
    ]
