# Generated by Django 3.0.2 on 2020-02-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='connected_client',
            field=models.BooleanField(default=False),
        ),
    ]
