# Generated by Django 3.0.2 on 2020-02-05 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_roster_connected_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchclient',
            name='sc2_profile',
        ),
        migrations.AddField(
            model_name='matchclient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
