# Generated by Django 3.0.3 on 2020-03-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200303_0225'),
        ('api', '0024_auto_20200213_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchstream',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='connected_client',
        ),
        migrations.RemoveField(
            model_name='twitchstream',
            name='user',
        ),
        migrations.AddField(
            model_name='twitchstream',
            name='social_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.SocialAccount'),
            preserve_default=False,
        ),
    ]
