# Generated by Django 3.0.4 on 2020-03-29 02:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200303_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
