# Generated by Django 3.0.4 on 2020-03-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_roster_lane'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventName',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('base_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameUnitStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('made', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('killed', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_unit_stats', to='api.Match')),
                ('opposing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SC2Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_unit_stats', to='api.SC2Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game_time', models.FloatField(max_length=20)),
                ('sequence', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('total_score', models.IntegerField()),
                ('minerals_on_hand', models.IntegerField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GameEventName')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='api.Match')),
                ('opposing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.SC2Profile')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_events', to='api.SC2Profile')),
            ],
            options={
                'unique_together': {('key', 'match', 'profile', 'sequence')},
            },
        ),
    ]
