# Generated by Django 3.0.4 on 2020-03-30 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_gameevent_gameeventname_gameunit_gameunitstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField()),
                ('minerals_on_hand', models.IntegerField()),
                ('game_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_points', to='api.GameEvent')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SC2Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
