# Generated by Django 3.0.4 on 2020-03-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_chartpoints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameevent',
            unique_together={('key', 'match', 'profile', 'game_time')},
        ),
    ]
