# Generated by Django 3.0.4 on 2020-04-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200330_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game_time', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.Match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentProfileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('left_game', models.BooleanField(default=False)),
                ('eliminated', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(default=0)),
                ('technology_resources', models.IntegerField(default=0)),
                ('lost_resources', models.IntegerField(default=0)),
                ('supply_on_hand', models.IntegerField(default=0)),
                ('supply_threshold', models.IntegerField(default=0)),
                ('eliminated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SC2Profile')),
                ('lane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.SC2Profile')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='api.Match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SC2Profile')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SegmentUnitStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('killed', models.IntegerField(default=0)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Segment')),
                ('segment_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_stats', to='api.SegmentProfileItem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.SegmentMeasure'),
        ),
        migrations.CreateModel(
            name='MatchMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game_time', models.FloatField()),
                ('message_type', models.CharField(choices=[('all_chat', 'All Chat'), ('allied_chat', 'Allied Chat')], max_length=100)),
                ('message', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.Match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.SC2Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
