# Generated by Django 3.0.4 on 2020-04-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200405_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameevent',
            old_name='sequence',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='segmentprofileitem',
            old_name='lost_resources',
            new_name='army_value',
        ),
        migrations.RenameField(
            model_name='segmentprofileitem',
            old_name='supply_on_hand',
            new_name='lost_tech_value',
        ),
        migrations.RenameField(
            model_name='segmentprofileitem',
            old_name='supply_threshold',
            new_name='minerals_on_hand',
        ),
        migrations.RenameField(
            model_name='segmentprofileitem',
            old_name='technology_resources',
            new_name='tech_damage_value',
        ),
        migrations.AddField(
            model_name='segmentprofileitem',
            name='tech_value',
            field=models.IntegerField(default=0),
        ),
    ]
