# Generated by Django 3.0.4 on 2020-04-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200405_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='leaderboard_ranking',
            field=models.IntegerField(default=0),
        ),
    ]
