# Generated by Django 3.0.4 on 2020-04-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_match_game_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('carried', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winners', to='api.Match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='api.SC2Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchLoser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('left_game', models.BooleanField()),
                ('game_time', models.FloatField()),
                ('victim_number', models.IntegerField()),
                ('killer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.SC2Profile')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_losers', to='api.Match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='api.SC2Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
