# Generated by Django 3.0.4 on 2020-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200411_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentunitstat',
            name='cancelled',
            field=models.IntegerField(default=0),
        ),
    ]
