# Generated by Django 3.0.4 on 2020-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_segmentunitstat_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='measure',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='SegmentMeasure',
        ),
    ]
