# Generated by Django 3.0.4 on 2020-04-12 23:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200326_1010'),
        ('api', '0041_auto_20200411_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchstream',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='twitchstream',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_streams', to='accounts.SocialAccount'),
        ),
    ]
