# Generated by Django 3.0.5 on 2020-04-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20200413_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='toon',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='mode',
            field=models.CharField(default='2v2v2v2', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='api.SC2Profile'),
            preserve_default=False,
        ),
    ]
