# Generated by Django 3.0.5 on 2020-04-19 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0044_auto_20200418_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchstream',
            name='user',
            field=models.ForeignKey(default='224734305581137921', on_delete=django.db.models.deletion.CASCADE, related_name='twitch_streams', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
