# Generated by Django 3.0.5 on 2020-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_twitchstream_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='details',
        ),
        migrations.AddField(
            model_name='match',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
