# Generated by Django 3.0.5 on 2020-04-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200428_0629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameevent',
            unique_together={('key', 'match', 'profile', 'opposing_profile', 'game_time')},
        ),
    ]
