# Generated by Django 3.0.5 on 2020-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200429_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sc2profile',
            options={'ordering': ('name',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='matchteam',
            name='victim_number',
            field=models.IntegerField(default=0),
        ),
    ]
