# Generated by Django 3.0.6 on 2020-06-29 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_match_observers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Match')),
            ],
            bases=('api.match',),
        ),
    ]
