# Generated by Django 3.0.6 on 2020-06-29 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20200629_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRoster',
            fields=[
                ('roster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Roster')),
            ],
            bases=('api.roster',),
        ),
    ]
