# Generated by Django 3.0.8 on 2020-08-30 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0056_temproster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmatch',
            name='match_ptr',
        ),
        migrations.RemoveField(
            model_name='temproster',
            name='roster_ptr',
        ),
        migrations.AddField(
            model_name='match',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MatchClient',
        ),
        migrations.DeleteModel(
            name='TempMatch',
        ),
        migrations.DeleteModel(
            name='TempRoster',
        ),
    ]
