# Generated by Django 3.0.8 on 2020-12-25 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20200830_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='lane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lane_rosters', to='api.SC2Profile'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='measure',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='segmentprofileitem',
            name='lane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lane_segments', to='api.SC2Profile'),
        ),
        migrations.AlterField(
            model_name='segmentprofileitem',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_segments', to='api.Match'),
        ),
        migrations.AlterField(
            model_name='segmentprofileitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_segments', to='api.SC2Profile'),
        ),
        migrations.AlterField(
            model_name='segmentunitstat',
            name='created',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='map_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
