# Generated by Django 3.0.3 on 2020-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200218_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
