# Generated by Django 3.0.3 on 2020-03-03 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200218_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='username',
            field=models.CharField(default='No Username', max_length=200),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
