# Generated by Django 3.0.4 on 2020-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200303_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
